[package]
name = "proddle"
version = "0.2.1"
authors = ["Dan Rammer <hamersaw@bushpath.com>"]

[build-dependencies]
capnpc = "0.7"

[dependencies]
bincode = {git="https://github.com/TyOverby/bincode"}
bson = "0.7"
clap = "2.19"
curl = "0.4"
mongodb = "0.2"
serde = "1.0"
serde_derive = "1.0"
